export { CORS } from './cors'
export const SEQUELIZE = 'SEQUELIZE'

// REPOSITORIES
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const WORKHOUR_REPOSITORY = 'WORKHOUR_REPOSITORY'
export const APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY'
export const APPOINTMENTSLOTS_REPOSITORY = 'APPOINTMENTSLOTS_REPOSITORY'
export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY'
export const MEMBER_REPOSITORY = 'MEMBER_REPOSITORY'
export const SERVICES_REPOSITORY = 'SERVICES_REPOSITORY'
export const CUSTOMERS_REPOSITORY = 'CUSTOMERS_REPOSITORY'
export const ENTERPRISE_REPOSITORY = 'ENTERPRISE_REPOSITORY'
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY'
export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY'
export const PAYMENT_PLAN_REPOSITORY = 'PAYMENT_PLAN_REPOSITORY'
export const SUBSCRIPTION_REPOSITORY = 'SUBSCRIPTION_REPOSITORY'
// ENVIROMENTS
export const DEVELOPMENT = 'development'
export const TEST = 'test'
export const PRODUCTION = 'production'

// ENVIROMENTS TYPES
export type enviromentType =
	| typeof DEVELOPMENT
	| typeof TEST
	| typeof PRODUCTION
